from typing import Any, Callable


class Model:
    """Live2D Cubism 2.x application model（与 live2d.v3.Model 统一 API）。"""

    # ---- 加载 / 版本 ----
    def LoadModelJson(self, path: str, create_renderer: bool = True) -> None:
        """Load model from .model.json file."""
        ...
    def LoadFromJsonString(self, json_data: str, create_renderer: bool = True, root_path: str = "") -> None:
        """Load model from an in-memory .model.json string; asset paths inside the json
        are used as-is (absolute) or resolved against root_path (relative).

        **IMPORTANT: json_data(str) must be indented due to CubismJson parsing defect**
        """
        ...
    def GetModelHomeDir(self) -> str:
        """Get model home directory."""
        ...
    def Version(self) -> int:
        """Get SDK version (2 for v2, 3 for v3)."""
        ...
    def IsV2(self) -> bool:
        """Check if model is Cubism 2.x."""
        ...
    def IsV3(self) -> bool:
        """Check if model is Cubism 3.x."""
        ...

    # ---- 更新 ----
    def Update(self, deltaSecs: float = -1.0) -> None:
        """Update model state. deltaSecs < 0（默认）: 墙钟自适配；>=0: delta 驱动。"""
        ...
    def UpdateMotion(self, deltaSecs: float) -> bool:
        """Update motion, returns True if updated."""
        ...
    def UpdateDrag(self, deltaSecs: float) -> None: ...
    def UpdateBreath(self, deltaSecs: float) -> None: ...
    def UpdateBlink(self, deltaSecs: float) -> None: ...
    def UpdateExpression(self, deltaSecs: float) -> None: ...
    def UpdatePhysics(self, deltaSecs: float) -> None: ...
    def UpdatePose(self, deltaSecs: float) -> None: ...

    # ---- 变换 ----
    def Resize(self, w: int, h: int) -> None: ...
    def Drag(self, x: float, y: float) -> None: ...
    def SetOffset(self, dx: float, dy: float) -> None: ...
    def SetOffsetX(self, x: float) -> None: ...
    def SetOffsetY(self, y: float) -> None: ...
    def SetScale(self, scale: float) -> None: ...
    def SetScaleX(self, scale: float) -> None: ...
    def SetScaleY(self, scale: float) -> None: ...
    def Rotate(self, deg: float) -> None: ...
    def GetMvp(self) -> tuple: ...

    # ---- 参数 ----
    def GetParamCount(self) -> int: ...
    def GetParamIds(self) -> list[str]: ...
    def GetParamValueByIndex(self, index: int) -> float: ...
    def GetParamMaxByIndex(self, index: int) -> float: ...
    def GetParamMinByIndex(self, index: int) -> float: ...
    def GetParamDefaultByIndex(self, index: int) -> float: ...
    def GetParamValueById(self, id: str) -> float: ...
    def GetParamMaxById(self, id: str) -> float: ...
    def GetParamMinById(self, id: str) -> float: ...
    def GetParamDefaultById(self, id: str) -> float: ...
    def SetParamByIndex(self, index: int, value: float, weight: float = 1.0) -> None: ...
    def SetParamById(self, id: str, value: float, weight: float = 1.0) -> None: ...
    def AddParamByIndex(self, index: int, value: float) -> None: ...
    def AddParamById(self, id: str, value: float) -> None: ...
    def SetSaveParamByIndex(self, index: int, value: float, weight: float = 1.0) -> None: ...
    def SetSaveParamById(self, id: str, value: float, weight: float = 1.0) -> None: ...
    def AddSaveParamByIndex(self, index: int, value: float) -> None: ...
    def AddSaveParamById(self, id: str, value: float) -> None: ...
    def LoadParameters(self) -> None: ...
    def SaveParameters(self) -> None: ...
    def ResetAllParameters(self) -> None: ...

    # ---- 部件 ----
    def GetPartCount(self) -> int: ...
    def GetPartId(self, index: int) -> str: ...
    def GetPartIds(self) -> list[str]: ...
    def SetPartOpacity(self, index: int, opacity: float) -> None: ...
    def SetPartScreenColor(self, index: int, r: float, g: float, b: float, a: float) -> None: ...
    def GetPartScreenColor(self, index: int) -> list[float]: ...
    def SetPartMultiplyColor(self, index: int, r: float, g: float, b: float, a: float) -> None: ...
    def GetPartMultiplyColor(self, index: int) -> list[float]: ...

    # ---- drawable ----
    def GetDrawableIds(self) -> list[str]: ...
    def GetDrawableVertices(self, index: int) -> list[float]: ...
    def GetDrawableVertexCount(self, index: int) -> int: ...
    def GetDrawableVertexIndexCount(self, index: int) -> int: ...
    def GetDrawableIndices(self, index: int) -> list[int]: ...
    def SetDrawableMultiplyColor(self, index: int, r: float, g: float, b: float, a: float) -> None: ...
    def SetDrawableScreenColor(self, index: int, r: float, g: float, b: float, a: float) -> None: ...

    # ---- 动作 ----
    def StartMotion(self, group: str, no: int, priority: int = 3,
                    onStart: Callable[[str, int], None] | None = None,
                    onFinish: Callable[[str, int], None] | None = None) -> None: ...
    def StartRandomMotion(self, group: str | None = None, priority: int = 3,
                          onStart: Callable[[str, int], None] | None = None,
                          onFinish: Callable[[str, int], None] | None = None) -> None: ...
    def IsMotionFinished(self) -> bool: ...
    def StopAllMotions(self) -> None: ...
    def LoadExtraMotion(self, group: str, path: str) -> int: ...
    def GetMotionGroupCount(self) -> int: ...
    def GetMotionCount(self, group: str) -> int: ...
    def GetMotionSound(self, group: str, no: int) -> str: ...
    def GetMotions(self) -> dict[str, list[dict[str, str]]]: ...
    def GetMotionGroups(self) -> dict[str, int]: ...

    # ---- 表情 ----
    def SetExpression(self, expressionId: str, fadeoutMs: float = -1.0) -> None:
        """fadeoutMs >= 0: 临时表情，到时恢复上一个持久表情。"""
        ...
    def SetRandomExpression(self, fadeoutMs: float = -1.0) -> str | None: ...
    def AddExpression(self, id: str) -> None: ...
    def RemoveExpression(self, id: str) -> None: ...
    def ResetExpressions(self) -> None: ...
    def ResetExpression(self) -> None: ...
    def GetExpressions(self) -> list[str]: ...
    def LoadExtraExpression(self, id: str, path: str) -> None: ...

    # ---- 命中测试 ----
    def HitPart(self, x: float, y: float, topOnly: bool = False) -> list[str]: ...
    def HitDrawable(self, x: float, y: float, topOnly: bool = False) -> list[str]: ...
    def IsAreaHit(self, area: str, x: float, y: float) -> bool: ...
    def IsPartHit(self, index: int, x: float, y: float) -> bool: ...
    def IsDrawableHit(self, index: int, x: float, y: float) -> bool: ...

    # ---- 画布 / 自动机制 / 其它 ----
    def GetCanvasSize(self) -> tuple[float, float]: ...
    def GetCanvasSizePixel(self) -> tuple[float, float]: ...
    def GetPixelsPerUnit(self) -> int: ...
    def SetAutoBreathParameterOnly(self, on: bool) -> None:
        """仅驱动呼吸参数，关闭时停止自动呼吸。"""
        ...

    def SetAutoBreath(self, on: bool) -> None: ...
    def SetAutoBlink(self, on: bool) -> None: ...
    def HasMocConsistencyFromFile(self, name: str) -> bool: ...
    def ResetPose(self) -> None: ...

    # ---- 渲染 ----
    def CreateRenderer(self, maskBufferCount: int = 1) -> None: ...
    def DestroyRenderer(self) -> None: ...
    def Draw(self) -> None: ...


def init() -> None:
    """Initialize platform manager."""
    ...

def glInit() -> None:
    """Initialize OpenGL function pointers."""
    ...

def glRelease() -> None:
    """Release OpenGL resources."""
    ...

def dispose() -> None:
    """Release all live2d resources."""
    ...

def clearBuffer(r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 0.0) -> None:
    """Clear color buffer."""
    ...

def enableLog(enable: bool) -> None:
    """Enable/disable log output."""
    ...

def isLogEnabled() -> bool:
    """Check if log is enabled."""
    ...

def setLogLevel(level: int) -> None:
    """Set log level."""
    ...

def getLogLevel() -> int:
    """Get current log level."""
    ...
