add_library(${V2_TARGET} STATIC
    Core/Id.cpp
    Core/BinaryReader.cpp
    Core/Live2DObjectFactory.cpp
    Core/ParamDefFloat.cpp
    Core/ParamDefSet.cpp
    Core/PartsData.cpp
    Core/PartsDataContext.cpp
    Core/Avatar.cpp
    Core/ModelImpl.cpp
    Core/ParamPivots.cpp
    Core/PivotManager.cpp
    Core/ModelContext.cpp
    Core/Deformer.cpp
    Core/AffineEnt.cpp
    Core/RotationDeformer.cpp
    Core/RotationContext.cpp
    Core/WarpDeformer.cpp
    Core/WarpContext.cpp
    Core/IDrawData.cpp
    Core/Mesh.cpp
    Core/GLRenderer.cpp
    Core/ClippingManagerOpenGL.cpp
    Core/ClipContext.cpp
    Core/UtInterpolate.cpp
    Core/UtSystem.cpp
    Framework/L2DMatrix44.cpp
    Framework/L2DModelMatrix.cpp
    Framework/L2DTargetPoint.cpp
    Framework/L2DEyeBlink.cpp
    Framework/L2DPose.cpp
    Framework/L2DPhysics.cpp
    Framework/PhysicsHair.cpp
    Framework/L2DExpressionMotion.cpp
    Framework/L2DMotionManager.cpp
    Framework/L2DBaseModel.cpp
    Framework/MatrixManagerV2.cpp
    Framework/Live2DMotion.cpp
    Model.cpp
)

